let item_fields = {
  url: '',
  user_sid: '',
  Year: '',
  MakeModel1: '',
  MakeModel2: '',
  Trim: '',
  BodyStyle: '',
  StockNumber: '',
  Vin: '',
  Kilometers: '',
  Price: '',
  MSRP: '',
  SpecialPrice: '',
  WholesalePrice: '',
  PurchasedFrom: '',
  Transmission: '',
  ExteriorColor: '',
  InteriorColor: '',
  SellerComments: '',
  VehicleOptions: '',
  pictures: '',
  Engine: '',
  DriveType: '',
  Doors: '',
  Passengers: '',
  FuelType: '',
  EngineSize: '',
  Height: '',
  Length: '',
  CityFuelEconomy: '',
  HwyFuelEconomy: '',
  Sold: '',
  WebsiteFeaturedAd: '',
  Condition: 'Used',
  vMake: '',
  vModel: '',
  Address: '',
  City: '',
  Location: '',
  Postcode: '',
  SellerType: 'Dealer',
  first_activation_date: '',
};

module.exports = item_fields;
